<?php
/**
 * LineItem
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  macropage\SDKs\ebay\rest\postorder
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * eBay Cancellation Search API
 *
 * API for searching eBay order cancellations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace macropage\SDKs\ebay\rest\postorder\Model;

use \ArrayAccess;
use \macropage\SDKs\ebay\rest\postorder\ObjectSerializer;

/**
 * LineItem Class Doc Comment
 *
 * @category Class
 * @package  macropage\SDKs\ebay\rest\postorder
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class LineItem implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'LineItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'itemId' => 'string',
        'transactionId' => 'string',
        'itemTitle' => 'string',
        'cancelQuantity' => 'int',
        'relistEligibilityCodeEnum' => 'string',
        'relistedItemId' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'itemId' => null,
        'transactionId' => null,
        'itemTitle' => null,
        'cancelQuantity' => null,
        'relistEligibilityCodeEnum' => null,
        'relistedItemId' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'itemId' => false,
        'transactionId' => false,
        'itemTitle' => false,
        'cancelQuantity' => false,
        'relistEligibilityCodeEnum' => false,
        'relistedItemId' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'itemId' => 'itemId',
        'transactionId' => 'transactionId',
        'itemTitle' => 'itemTitle',
        'cancelQuantity' => 'cancelQuantity',
        'relistEligibilityCodeEnum' => 'relistEligibilityCodeEnum',
        'relistedItemId' => 'relistedItemId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'itemId' => 'setItemId',
        'transactionId' => 'setTransactionId',
        'itemTitle' => 'setItemTitle',
        'cancelQuantity' => 'setCancelQuantity',
        'relistEligibilityCodeEnum' => 'setRelistEligibilityCodeEnum',
        'relistedItemId' => 'setRelistedItemId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'itemId' => 'getItemId',
        'transactionId' => 'getTransactionId',
        'itemTitle' => 'getItemTitle',
        'cancelQuantity' => 'getCancelQuantity',
        'relistEligibilityCodeEnum' => 'getRelistEligibilityCodeEnum',
        'relistedItemId' => 'getRelistedItemId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('itemId', $data ?? [], null);
        $this->setIfExists('transactionId', $data ?? [], null);
        $this->setIfExists('itemTitle', $data ?? [], null);
        $this->setIfExists('cancelQuantity', $data ?? [], null);
        $this->setIfExists('relistEligibilityCodeEnum', $data ?? [], null);
        $this->setIfExists('relistedItemId', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets itemId
     *
     * @return string|null
     */
    public function getItemId()
    {
        return $this->container['itemId'];
    }

    /**
     * Sets itemId
     *
     * @param string|null $itemId itemId
     *
     * @return self
     */
    public function setItemId($itemId)
    {
        if (is_null($itemId)) {
            throw new \InvalidArgumentException('non-nullable itemId cannot be null');
        }
        $this->container['itemId'] = $itemId;

        return $this;
    }

    /**
     * Gets transactionId
     *
     * @return string|null
     */
    public function getTransactionId()
    {
        return $this->container['transactionId'];
    }

    /**
     * Sets transactionId
     *
     * @param string|null $transactionId transactionId
     *
     * @return self
     */
    public function setTransactionId($transactionId)
    {
        if (is_null($transactionId)) {
            throw new \InvalidArgumentException('non-nullable transactionId cannot be null');
        }
        $this->container['transactionId'] = $transactionId;

        return $this;
    }

    /**
     * Gets itemTitle
     *
     * @return string|null
     */
    public function getItemTitle()
    {
        return $this->container['itemTitle'];
    }

    /**
     * Sets itemTitle
     *
     * @param string|null $itemTitle itemTitle
     *
     * @return self
     */
    public function setItemTitle($itemTitle)
    {
        if (is_null($itemTitle)) {
            throw new \InvalidArgumentException('non-nullable itemTitle cannot be null');
        }
        $this->container['itemTitle'] = $itemTitle;

        return $this;
    }

    /**
     * Gets cancelQuantity
     *
     * @return int|null
     */
    public function getCancelQuantity()
    {
        return $this->container['cancelQuantity'];
    }

    /**
     * Sets cancelQuantity
     *
     * @param int|null $cancelQuantity cancelQuantity
     *
     * @return self
     */
    public function setCancelQuantity($cancelQuantity)
    {
        if (is_null($cancelQuantity)) {
            throw new \InvalidArgumentException('non-nullable cancelQuantity cannot be null');
        }
        $this->container['cancelQuantity'] = $cancelQuantity;

        return $this;
    }

    /**
     * Gets relistEligibilityCodeEnum
     *
     * @return string|null
     */
    public function getRelistEligibilityCodeEnum()
    {
        return $this->container['relistEligibilityCodeEnum'];
    }

    /**
     * Sets relistEligibilityCodeEnum
     *
     * @param string|null $relistEligibilityCodeEnum relistEligibilityCodeEnum
     *
     * @return self
     */
    public function setRelistEligibilityCodeEnum($relistEligibilityCodeEnum)
    {
        if (is_null($relistEligibilityCodeEnum)) {
            throw new \InvalidArgumentException('non-nullable relistEligibilityCodeEnum cannot be null');
        }
        $this->container['relistEligibilityCodeEnum'] = $relistEligibilityCodeEnum;

        return $this;
    }

    /**
     * Gets relistedItemId
     *
     * @return int|null
     */
    public function getRelistedItemId()
    {
        return $this->container['relistedItemId'];
    }

    /**
     * Sets relistedItemId
     *
     * @param int|null $relistedItemId relistedItemId
     *
     * @return self
     */
    public function setRelistedItemId($relistedItemId)
    {
        if (is_null($relistedItemId)) {
            throw new \InvalidArgumentException('non-nullable relistedItemId cannot be null');
        }
        $this->container['relistedItemId'] = $relistedItemId;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


