<?php
/**
 * CancellationSearchApi
 * PHP version 7.4
 *
 * @category Class
 * @package  macropage\SDKs\ebay\rest\postorder
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * eBay Cancellation Search API
 *
 * API for searching eBay order cancellations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace macropage\SDKs\ebay\rest\postorder\API;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use macropage\SDKs\ebay\rest\postorder\ApiException;
use macropage\SDKs\ebay\rest\postorder\Configuration;
use macropage\SDKs\ebay\rest\postorder\HeaderSelector;
use macropage\SDKs\ebay\rest\postorder\ObjectSerializer;

/**
 * CancellationSearchApi Class Doc Comment
 *
 * @category Class
 * @package  macropage\SDKs\ebay\rest\postorder
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CancellationSearchApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'searchCancellations' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation searchCancellations
     *
     * Search for order cancellations
     *
     * @param  string $cancelId cancelId (optional)
     * @param  string $creationDateRangeFrom creationDateRangeFrom (optional)
     * @param  string $creationDateRangeTo creationDateRangeTo (optional)
     * @param  string $itemId itemId (optional)
     * @param  string $legacyOrderId legacyOrderId (optional)
     * @param  string $limit limit (optional)
     * @param  string $offset offset (optional)
     * @param  string $role role (optional)
     * @param  string $sort sort (optional)
     * @param  string $transactionId transactionId (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchCancellations'] to see the possible values for this operation
     *
     * @throws \macropage\SDKs\ebay\rest\postorder\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \macropage\SDKs\ebay\rest\postorder\Model\FindCancelResponse
     */
    public function searchCancellations($cancelId = null, $creationDateRangeFrom = null, $creationDateRangeTo = null, $itemId = null, $legacyOrderId = null, $limit = null, $offset = null, $role = null, $sort = null, $transactionId = null, string $contentType = self::contentTypes['searchCancellations'][0])
    {
        list($response) = $this->searchCancellationsWithHttpInfo($cancelId, $creationDateRangeFrom, $creationDateRangeTo, $itemId, $legacyOrderId, $limit, $offset, $role, $sort, $transactionId, $contentType);
        return $response;
    }

    /**
     * Operation searchCancellationsWithHttpInfo
     *
     * Search for order cancellations
     *
     * @param  string $cancelId (optional)
     * @param  string $creationDateRangeFrom (optional)
     * @param  string $creationDateRangeTo (optional)
     * @param  string $itemId (optional)
     * @param  string $legacyOrderId (optional)
     * @param  string $limit (optional)
     * @param  string $offset (optional)
     * @param  string $role (optional)
     * @param  string $sort (optional)
     * @param  string $transactionId (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchCancellations'] to see the possible values for this operation
     *
     * @throws \macropage\SDKs\ebay\rest\postorder\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \macropage\SDKs\ebay\rest\postorder\Model\FindCancelResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function searchCancellationsWithHttpInfo($cancelId = null, $creationDateRangeFrom = null, $creationDateRangeTo = null, $itemId = null, $legacyOrderId = null, $limit = null, $offset = null, $role = null, $sort = null, $transactionId = null, string $contentType = self::contentTypes['searchCancellations'][0])
    {
        $request = $this->searchCancellationsRequest($cancelId, $creationDateRangeFrom, $creationDateRangeTo, $itemId, $legacyOrderId, $limit, $offset, $role, $sort, $transactionId, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\macropage\SDKs\ebay\rest\postorder\Model\FindCancelResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\macropage\SDKs\ebay\rest\postorder\Model\FindCancelResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\macropage\SDKs\ebay\rest\postorder\Model\FindCancelResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\macropage\SDKs\ebay\rest\postorder\Model\FindCancelResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\macropage\SDKs\ebay\rest\postorder\Model\FindCancelResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation searchCancellationsAsync
     *
     * Search for order cancellations
     *
     * @param  string $cancelId (optional)
     * @param  string $creationDateRangeFrom (optional)
     * @param  string $creationDateRangeTo (optional)
     * @param  string $itemId (optional)
     * @param  string $legacyOrderId (optional)
     * @param  string $limit (optional)
     * @param  string $offset (optional)
     * @param  string $role (optional)
     * @param  string $sort (optional)
     * @param  string $transactionId (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchCancellations'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchCancellationsAsync($cancelId = null, $creationDateRangeFrom = null, $creationDateRangeTo = null, $itemId = null, $legacyOrderId = null, $limit = null, $offset = null, $role = null, $sort = null, $transactionId = null, string $contentType = self::contentTypes['searchCancellations'][0])
    {
        return $this->searchCancellationsAsyncWithHttpInfo($cancelId, $creationDateRangeFrom, $creationDateRangeTo, $itemId, $legacyOrderId, $limit, $offset, $role, $sort, $transactionId, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation searchCancellationsAsyncWithHttpInfo
     *
     * Search for order cancellations
     *
     * @param  string $cancelId (optional)
     * @param  string $creationDateRangeFrom (optional)
     * @param  string $creationDateRangeTo (optional)
     * @param  string $itemId (optional)
     * @param  string $legacyOrderId (optional)
     * @param  string $limit (optional)
     * @param  string $offset (optional)
     * @param  string $role (optional)
     * @param  string $sort (optional)
     * @param  string $transactionId (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchCancellations'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchCancellationsAsyncWithHttpInfo($cancelId = null, $creationDateRangeFrom = null, $creationDateRangeTo = null, $itemId = null, $legacyOrderId = null, $limit = null, $offset = null, $role = null, $sort = null, $transactionId = null, string $contentType = self::contentTypes['searchCancellations'][0])
    {
        $returnType = '\macropage\SDKs\ebay\rest\postorder\Model\FindCancelResponse';
        $request = $this->searchCancellationsRequest($cancelId, $creationDateRangeFrom, $creationDateRangeTo, $itemId, $legacyOrderId, $limit, $offset, $role, $sort, $transactionId, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    print_r($returnType);
                    print_r($content);

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'searchCancellations'
     *
     * @param  string $cancelId (optional)
     * @param  string $creationDateRangeFrom (optional)
     * @param  string $creationDateRangeTo (optional)
     * @param  string $itemId (optional)
     * @param  string $legacyOrderId (optional)
     * @param  string $limit (optional)
     * @param  string $offset (optional)
     * @param  string $role (optional)
     * @param  string $sort (optional)
     * @param  string $transactionId (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchCancellations'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function searchCancellationsRequest($cancelId = null, $creationDateRangeFrom = null, $creationDateRangeTo = null, $itemId = null, $legacyOrderId = null, $limit = null, $offset = null, $role = null, $sort = null, $transactionId = null, string $contentType = self::contentTypes['searchCancellations'][0])
    {
        // verify the required parameter 'xEBAYCMARKETPLACEID' is set
        if (empty($this->config->getMarketplaceId())) {
            throw new \InvalidArgumentException(
                'Missing the required parameter in header X-EBAY-C-MARKETPLACE-ID'
            );
        }

        $resourcePath = '/cancellation/search';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $cancelId,
            'cancel_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $creationDateRangeFrom,
            'creation_date_range_from', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $creationDateRangeTo,
            'creation_date_range_to', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $itemId,
            'item_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $legacyOrderId,
            'legacy_order_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $offset,
            'offset', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $role,
            'role', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort,
            'sort', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $transactionId,
            'transaction_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = $this->config->getAccessToken();
        }
        $headers['X-EBAY-C-MARKETPLACE-ID'] = $this->config->getMarketplaceId();

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
