<?php
/**
 * CancellationSearchApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  macropage\SDKs\ebay\rest\postorder
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * eBay Cancellation Search API
 *
 * API for searching eBay order cancellations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace macropage\SDKs\ebay\rest\postorder\Test\Api;

use \macropage\SDKs\ebay\rest\postorder\Configuration;
use \macropage\SDKs\ebay\rest\postorder\ApiException;
use \macropage\SDKs\ebay\rest\postorder\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CancellationSearchApiTest Class Doc Comment
 *
 * @category Class
 * @package  macropage\SDKs\ebay\rest\postorder
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CancellationSearchApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for searchCancellations
     *
     * Search for order cancellations.
     *
     */
    public function testSearchCancellations()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
